#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ipe
Version  : 7.2.26
Release  : 6
URL      : https://github.com/otfried/ipe/releases/download/v7.2.26/ipe-7.2.26-src.tar.gz
Source0  : https://github.com/otfried/ipe/releases/download/v7.2.26/ipe-7.2.26-src.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
BuildRequires : gsl-dev
BuildRequires : lua-dev
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(QtSpell-qt5)
BuildRequires : pkgconfig(gsl)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libspiro)
BuildRequires : pkgconfig(zlib)

%description
Ipe 7.2.26
July, 2022
Ipe extensible drawing editor
=============================

%prep
%setup -q -n ipe-7.2.26
cd %{_builddir}/ipe-7.2.26

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1672178102
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
pushd src
make  %{?_smp_mflags}  IPEPREFIX=/usr IPELIBDIR=/usr/lib64 LUA_PACKAGE=lua
popd


%install
export SOURCE_DATE_EPOCH=1672178102
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ipe
cp %{_builddir}/ipe-%{version}/gpl.txt %{buildroot}/usr/share/package-licenses/ipe/8624bcdae55baeef00cd11d5dfcfa60f68710a02
pushd src
%make_install IPEPREFIX=/usr IPELIBDIR=/usr/lib64 LUA_PACKAGE=lua
popd

%files
%defattr(-,root,root,-)
